begin;

create table if not exists public.book_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  review_text text check (review_text is null or char_length(review_text) <= 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, book_id)
);

create index if not exists book_reviews_book_id_idx
  on public.book_reviews(book_id);

create index if not exists book_reviews_user_id_idx
  on public.book_reviews(user_id);

alter table public.book_reviews enable row level security;

drop policy if exists "Anyone can read book reviews" on public.book_reviews;
create policy "Anyone can read book reviews"
  on public.book_reviews
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Users create own book reviews" on public.book_reviews;
create policy "Users create own book reviews"
  on public.book_reviews
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users update own book reviews" on public.book_reviews;
create policy "Users update own book reviews"
  on public.book_reviews
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users delete own book reviews" on public.book_reviews;
create policy "Users delete own book reviews"
  on public.book_reviews
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

grant select on public.book_reviews to anon, authenticated;
grant insert, update, delete on public.book_reviews to authenticated;
grant usage, select on sequence public.book_reviews_id_seq to authenticated;

drop trigger if exists set_book_reviews_updated_at on public.book_reviews;
create trigger set_book_reviews_updated_at
before update on public.book_reviews
for each row execute function public.set_updated_at();

drop policy if exists "Users delete own books" on public.user_books;
create policy "Users delete own books"
  on public.user_books
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

grant delete on public.user_books to authenticated;

create table if not exists public.platform_settings (
  id text primary key,
  allow_registrations boolean not null default true,
  require_approval boolean not null default true,
  require_email_verification boolean not null default true,
  verification_enabled boolean not null default true,
  verified_lift_limits boolean not null default true,
  verification_label text not null default 'Verified',
  allow_club_creation boolean not null default true,
  allow_private_clubs boolean not null default true,
  club_limit smallint not null default 5 check (club_limit between 1 and 100),
  ballot_choice_count smallint not null default 3 check (ballot_choice_count between 2 and 10),
  marketplace_enabled boolean not null default true,
  preferred_affiliate text not null default 'Bookshop.org',
  affiliate_disclosure text not null default 'Paper Gremlin may earn a commission from qualifying purchases made through affiliate links.',
  premium_price numeric(10,2) not null default 10 check (premium_price >= 0),
  premium_tokens integer not null default 1000 check (premium_tokens >= 0),
  coins_per_dollar integer not null default 100 check (coins_per_dollar > 0),
  reserve_percent numeric(6,2) not null default 100 check (reserve_percent between 0 and 100),
  disable_club_links boolean not null default true,
  disable_club_images boolean not null default true,
  device_enforcement boolean not null default true,
  maintenance_mode boolean not null default false,
  site_notice text not null default '',
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint platform_settings_global_row check (id = 'global')
);

insert into public.platform_settings (id)
values ('global')
on conflict (id) do nothing;

alter table public.platform_settings enable row level security;

drop policy if exists "Site admins read platform settings" on public.platform_settings;
create policy "Site admins read platform settings"
  on public.platform_settings
  for select
  to authenticated
  using (public.is_site_admin((select auth.uid())));

drop policy if exists "Site admins insert platform settings" on public.platform_settings;
create policy "Site admins insert platform settings"
  on public.platform_settings
  for insert
  to authenticated
  with check (public.is_site_admin((select auth.uid())) and updated_by = (select auth.uid()));

drop policy if exists "Site admins update platform settings" on public.platform_settings;
create policy "Site admins update platform settings"
  on public.platform_settings
  for update
  to authenticated
  using (public.is_site_admin((select auth.uid())))
  with check (public.is_site_admin((select auth.uid())) and updated_by = (select auth.uid()));

grant select, insert, update on public.platform_settings to authenticated;

drop trigger if exists set_platform_settings_updated_at on public.platform_settings;
create trigger set_platform_settings_updated_at
before update on public.platform_settings
for each row execute function public.set_updated_at();

create or replace function public.create_forum_thread(
  p_club_id bigint,
  p_title text,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  clean_title text := btrim(coalesce(p_title, ''));
  clean_body text := btrim(coalesce(p_body, ''));
  new_thread_id bigint;
begin
  if caller_id is null then
    raise exception 'Authentication required.';
  end if;

  if not public.is_active_club_member(p_club_id) then
    raise exception 'Only active club members can create discussions.';
  end if;

  if clean_title = '' or char_length(clean_title) > 180 then
    raise exception 'Discussion titles must be between 1 and 180 characters.';
  end if;

  if clean_body = '' or char_length(clean_body) > 20000 then
    raise exception 'Opening posts must be between 1 and 20,000 characters.';
  end if;

  insert into public.forum_threads (
    club_id,
    author_id,
    title,
    is_pinned,
    is_locked,
    is_hidden
  ) values (
    p_club_id,
    caller_id,
    clean_title,
    false,
    false,
    false
  )
  returning id into new_thread_id;

  insert into public.forum_posts (
    thread_id,
    author_id,
    body,
    is_hidden
  ) values (
    new_thread_id,
    caller_id,
    clean_body,
    false
  );

  return new_thread_id;
end;
$$;

revoke all on function public.create_forum_thread(bigint, text, text) from public;
revoke all on function public.create_forum_thread(bigint, text, text) from anon;
grant execute on function public.create_forum_thread(bigint, text, text) to authenticated;

commit;
